// Generated by the ${TBLipsContext.getPluginName()} at ${Date}
package $componentsPackage;

import org.treasureboat.webcore.appserver.TBContext;
import org.treasureboat.webcore.components.TBComponent;

public class Main extends TBComponent {
	
	private static final long serialVersionUID = 1L;

	public Main(TBContext context) {
		super(context);
	}
}
