// Generated by the ${TBLipsContext.getPluginName()} at ${Date}
package $basePackage;

import org.treasureboat.webcore.appserver.TBApplication;
import lombok.extern.slf4j.Slf4j;

@Slf4j
public class Application extends TBApplication {

	//********************************************************************
	//  BOOT : アプリケーション起動開始
	//********************************************************************
	
	public static void main(String[] argv) {
		TBApplication.main(argv, Application.class);
	}

	//********************************************************************
	//  Constructor : コンストラクタ
	//********************************************************************


	public Application() {
	    super();
	    
	    log.info("=================================================");
	    log.info("Welcome to " + name() + " !");
	    log.info("=================================================");
	  	
	    /* ** put your initialization code in here ** */
	}

	//********************************************************************
	//  Setup : セットアップ
	//********************************************************************

}
