// Generated by the ${TBLipsContext.getPluginName()} at ${Date}
package $basePackage;

import org.treasureboat.webcore.appserver.TBDirectAction;
import org.treasureboat.webcore.appserver.TBRequest;
import org.treasureboat.webcore.appserver.iface.ITBWActionResults;
import lombok.extern.slf4j.Slf4j;

import ${componentsPackage}.Main;

@Slf4j
public class DirectAction extends TBDirectAction {
	
	public DirectAction(TBRequest request) {
		super(request);
	}

	public ITBWActionResults standard() {
		return pageWithName(Main.class.getName());
	}
}
