// Generated by the ${TBLipsContext.getPluginName()} at ${Date}
package $basePackage;

import org.treasureboat.webcore.appserver.TBSession;
import lombok.extern.slf4j.Slf4j;


@Slf4j
public class Session extends TBSession {
	
	private static final long serialVersionUID = 1L;

	public Session() {
	}
}
